apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: monitoring
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:+0d7+vuFU9s2F+nOVEPJ5kV19dysj5puE8yNdZLe4hjn1zLN0+0F8mrA8fkvc0ntGEIC90U=,iv:J7J5orNdPAIQxfDgW7GHX+gVwynFFVkmYdIwu+lNWxg=,tag:iuhrnkL1viz+kP1Mp6UOSA==,type:str]
sops:
    age:
        - recipient: age185zaa854vh74f7yprqfxxurta4ywfdrwh865f42xys529e5zd5tq0ldhsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSzNkQnZiQUN1dVRrUkVW
            dEJkM1FUQUhwakl1Vy9tVG5QTG9VZkFjS2hrCnc4MzM4OVphUFRiN2trSXBrc2tr
            bjRtZXBUR3FiQUk5L1FYRlVwdk1hME0KLS0tIEhhZzd0eldHYktvdTNZQUlManR2
            eDRXdWJLSkxsd1VOcURnV2JucGk2eWMKtV2pRjJ5eARDJLf5TXjESdcoUfZIT0HD
            wv9F5yaunVMWOAV3j8E1uHR9i+782NUnbpYrJY+TX95XDjIykdXRSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T12:38:55Z"
    mac: ENC[AES256_GCM,data:FsuT+8ETvCL7Ek+siQRd6/LkfQ8MLt5rb4gMLIs5nGmQNf+8jSuII2TGsmqRs3ZHJmDB/KHJZbbXIWfXjCGLfkOPzNDz+aLp2f3cb4rNLlb4QEHtQJA+TR8Vb7BBXELh2b8bHeN6FDmYy/5WMbXZp4s3uaiQnoo6IcdrZn/fOE4=,iv:3+/LwIZxbKfowEalFzQ80LGKWGLt//3he94coFdh8y8=,tag:VKbaQmwHQ6TEavn+MGbPpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
