{
 "title": "Game App — Full Stack Overview",
 "description": "Custom metrics for Game app hosted on Kubernetes cluster",
 "time": { "from": "2026-05-11T19:31:05.199Z", "to": "2026-05-11T21:07:02.552Z" },
 "panels": [
  {
   "title": "Memory Usage (Game)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"game\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections (Game)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"ttt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"game\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"ttt\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}