apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:cXYW4fE=,iv:wzzzXCtPOuw5g76npl0l6wnXpnwwM42yZBUbU0/PPe8=,tag:44mXMG4qPJQdhBrh5srsQQ==,type:str]
    admin-password: ENC[AES256_GCM,data:0temPTe71R2nncI=,iv:AxaGbXV25Bq6fIjgEtjTdhj2W5C5CF/KNTw3pN0mbFs=,tag:4Bw23J/Buk/tnfWDmQqYOg==,type:str]
sops:
    age:
        - recipient: age185zaa854vh74f7yprqfxxurta4ywfdrwh865f42xys529e5zd5tq0ldhsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y1RlUmRyY2hqZ3dnaDJX
            blczeER6dFdPemQzOVN1K0hRcGhkL3dOaVNvClVLcjJBWlQ2WEczdi8rb2RjTUYv
            OWM4N24wU1NhOFFjWGQ2cVMrYkhCb0EKLS0tIEMveG8xQ1BTZVdpd1R3cEI4NE9t
            Y0M5VENFUzJFV01jdTJ6V1ltUGhlalkKKLk78bkU8upmOZ4dOx+DDqVVeqcGOnCN
            EWIBua7uT72ktMa4wOqt2CzIrwqzLDGu8C4Ml5hTosillXICxsyJiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T22:16:43Z"
    mac: ENC[AES256_GCM,data:dYqwN0OwOKDLVVO6V/Pi64WQBFJAomUgqUd9Fd2mucrhGzaO/9jMkkGtxlBUkTscOOqiQHU02/GcGdwosM6SpLUHvalMCPuOHth62NcxFKRzmsGVrtQGFCzGfCltAbg8/J2Qx22SAXggwPlcyb6NlGoIQ/RdJBQlp3BDTRWF4Xs=,iv:h8sng+kqLusHwl1dgf5p6AHPc+u0xgNSzGsCY8Jka0c=,tag:lJP25ySWFMmgc+0j0yJKuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
