postgres:
  name: postgres
  image: postgres:16-alpine
  port: 5432
  pvcName: postgres-pvc
  storage: 2Gi

web:
  name: game-web
  image: appoc14/tictactoe-web:1.0
  servicePort: 80
  containerPort: 5000
  serviceType: ClusterIP

replicaCount: 1

ingress:
  enabled: true
  name: game-ingress
  host: game.x4.com
  path: /
  pathType: Prefix
