apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: singlepod
  namespace: singlepod
spec:
  interval: 10m
  chart:
    spec:
      chart: ../../../Helm/singlepod/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  values:
    replicaCount: 1
