apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
  namespace: bookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf

  template:
    metadata:
      labels:
        app: bookshelf

    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: bookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.2
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          envFrom:
            - configMapRef:
                name: bookshelf-configmap
          readinessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3005
            initialDelaySeconds: 30
            periodSeconds: 10

          ports:
            - containerPort: 3005
              protocol: TCP

          volumeMounts:
            - mountPath: /config
              name: bookshelf-config
            - mountPath: /metadata
              name: bookshelf-metadata
            - mountPath: /audiobooks
              name: bookshelf-audiobooks

      restartPolicy: Always

      volumes:
        - name: bookshelf-config
          persistentVolumeClaim:
            claimName: bookshelf-config
        - name: bookshelf-metadata
          persistentVolumeClaim:
            claimName: bookshelf-metadata
        - name: bookshelf-audiobooks
          persistentVolumeClaim:
            claimName: bookshelf-audiobooks
