apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:PHV+,iv:pfJxAlzPuhWFWPY3JgTe+ZzBoY2aMKObAZK6oGwH6CE=,tag:4vdwuR0z8bcprB6kLR93UQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cQCR,iv:QSQazpqS+4IqWPVGYgicjHDJjmOt6MiFp3k7bubXe+s=,tag:QBtJi0R3R2oEGyuKIMJizg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8oc+WLJt1g==,iv:9MbnCO4wcuIRjxBY8y6Rpl0adlojyfgt8tMG+1d88ow=,tag:so0n6WDGQ1mtydgsOPv2aw==,type:str]
sops:
    age:
        - recipient: age185zaa854vh74f7yprqfxxurta4ywfdrwh865f42xys529e5zd5tq0ldhsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NzdyL2gxODcybEF4RGtN
            TDZ2cHRmbzdiT2srTlNjZVkwSDRWZ1NZUlc4Cm80WHV1Q25LZTBGMkpWbjRQRTJv
            dHhHTGlpVXRKVjYyVUJUM1A5aTgzWGMKLS0tIHhrUVJrVmNMcTVLOFh0OE93U3g0
            NEdUTytMMk9sK20wdk9tZXJEYjFDekkK5ajlJ7rk5Umprhwp5DFB1jjOtu7X33YK
            zowkYlhh+0NdE/qgS+NuzLb9Mf0V3+2bdVmJpQuRgQPQYIvoJ0HHRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T15:50:08Z"
    mac: ENC[AES256_GCM,data:I2VipImte5GLa9P7LYhxgwWyzjz9CCEPW8iefD9w+e+ng5tlvANTRaaDImQuhkSCnJHikeRx2RGeNyXocKOi8hrFJ3RbCDwdkMivqeAx+zq0BqRmRDBxgi2FUHDv2k+SD9RGfZBNNFxcI3nLnjJfjyGxiG1BskbJF/ivF6wKoss=,iv:WDLRSgtf9oKIm26CoKAcSrdUGCUZ3nUGeeWP1YfAndk=,tag:9esw41wseY9PrQYdDL+tzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: web-secret
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:ea72ori4NtlWth93BIwcGlL2rlCPy5PRtFDIXBmwf4MCgYGW85fMpHff,iv:n7SYHo6n4SIrcDdSFcnSKstEtBdyFvb4SNt3lwIqHWE=,tag:IbF8mwYrPKl7mjSNaKADEw==,type:str]
sops:
    age:
        - recipient: age185zaa854vh74f7yprqfxxurta4ywfdrwh865f42xys529e5zd5tq0ldhsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NzdyL2gxODcybEF4RGtN
            TDZ2cHRmbzdiT2srTlNjZVkwSDRWZ1NZUlc4Cm80WHV1Q25LZTBGMkpWbjRQRTJv
            dHhHTGlpVXRKVjYyVUJUM1A5aTgzWGMKLS0tIHhrUVJrVmNMcTVLOFh0OE93U3g0
            NEdUTytMMk9sK20wdk9tZXJEYjFDekkK5ajlJ7rk5Umprhwp5DFB1jjOtu7X33YK
            zowkYlhh+0NdE/qgS+NuzLb9Mf0V3+2bdVmJpQuRgQPQYIvoJ0HHRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T15:50:08Z"
    mac: ENC[AES256_GCM,data:I2VipImte5GLa9P7LYhxgwWyzjz9CCEPW8iefD9w+e+ng5tlvANTRaaDImQuhkSCnJHikeRx2RGeNyXocKOi8hrFJ3RbCDwdkMivqeAx+zq0BqRmRDBxgi2FUHDv2k+SD9RGfZBNNFxcI3nLnjJfjyGxiG1BskbJF/ivF6wKoss=,iv:WDLRSgtf9oKIm26CoKAcSrdUGCUZ3nUGeeWP1YfAndk=,tag:9esw41wseY9PrQYdDL+tzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
