apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: game
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:q2YU,iv:YNAJUND+kds4bnoRLs/Q7ZC3x5sSMwp2lqqkPgHmTwY=,tag:1mwvJhrkeOCgPydEzYLPLw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:iPFl,iv:go0Y6LlyTg/8Cr6oN5Hfti2zv6GY2VdRmEApBdkuVkE=,tag:871pXwdBaCO9zsZCOckueQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:z7yhMjktyg==,iv:8HBBdMu+2nt6fKu7ACb4xe2K/nfGWGUA1AUiTh/tMAI=,tag:gC5EBJjGae78S6cinrVVyg==,type:str]
sops:
    age:
        - recipient: age185zaa854vh74f7yprqfxxurta4ywfdrwh865f42xys529e5zd5tq0ldhsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMHRwVkxzWmZtczZvSnl1
            eVN5RzlwZFpESVVhQVFRdS9wZ2szdzl0R2hnCk1YQzFOcHNNQ3NFaDdRMjlMTUd5
            ZGJPbVdvUFhuNHFvNFBBK1VHQ2JtTXMKLS0tIHhRb1FxSzdCbkh0cDhkUFhMQ056
            NFphRmRtOWFIZHk1ZDIweVlLM2FWcncKhsGgLStBEp0pPZhtojIm2Lg+MwLkyBtV
            CfdHl3M2K0fX1kgXX+Z2HUsf0+kPJLgSBINVwdeduq1uN7UCx0I0QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T03:04:31Z"
    mac: ENC[AES256_GCM,data:AkfDNRi7psQuAIL/LKWvWvPRjhANrm/b+UZCzS8EXBL+rzHMxJxfS84S59PbcNr62rUVnrwU/gGN0+6XvpB6Rb/HonEUa+I+qo/jZXYWD0gtetTsFW5cCiHHhOhpFu9YAn3LdddMvd5VukDMT2KOb65T4JYJUdLtseVqikdq+6E=,iv:ew2Mx2Vwpwp/g1kiFsgRerMnSMlM23nvXB++jy20IJY=,tag:OvUDGiWGr3qkrLxmSwHuoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: web-secret
    namespace: game
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:fVvEdnoxVfN9CTpZNI6mMwBO0u5wWtA/T+kWZ7ssmnlND+5NS248Au0o,iv:EtzelEC3Qi0dU5CpzTmBHuONit76DDfTzeTjlip5Ntc=,tag:ob25SQNGrNjdeH/nhlcAAA==,type:str]
sops:
    age:
        - recipient: age185zaa854vh74f7yprqfxxurta4ywfdrwh865f42xys529e5zd5tq0ldhsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMHRwVkxzWmZtczZvSnl1
            eVN5RzlwZFpESVVhQVFRdS9wZ2szdzl0R2hnCk1YQzFOcHNNQ3NFaDdRMjlMTUd5
            ZGJPbVdvUFhuNHFvNFBBK1VHQ2JtTXMKLS0tIHhRb1FxSzdCbkh0cDhkUFhMQ056
            NFphRmRtOWFIZHk1ZDIweVlLM2FWcncKhsGgLStBEp0pPZhtojIm2Lg+MwLkyBtV
            CfdHl3M2K0fX1kgXX+Z2HUsf0+kPJLgSBINVwdeduq1uN7UCx0I0QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T03:04:31Z"
    mac: ENC[AES256_GCM,data:AkfDNRi7psQuAIL/LKWvWvPRjhANrm/b+UZCzS8EXBL+rzHMxJxfS84S59PbcNr62rUVnrwU/gGN0+6XvpB6Rb/HonEUa+I+qo/jZXYWD0gtetTsFW5cCiHHhOhpFu9YAn3LdddMvd5VukDMT2KOb65T4JYJUdLtseVqikdq+6E=,iv:ew2Mx2Vwpwp/g1kiFsgRerMnSMlM23nvXB++jy20IJY=,tag:OvUDGiWGr3qkrLxmSwHuoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
