apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - name: pg
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  type: {{ .Values.web.serviceType }}
  selector:
    app: {{ .Values.web.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.servicePort }}
      targetPort: {{ .Values.web.containerPort }}
      {{- if eq .Values.web.serviceType "NodePort" }}
      nodePort: {{ .Values.web.nodePort }}
      {{- end }}
