apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: game.x4.com
    http:
    paths:
      - pathType: Prefix
      path: "/"
      backend:
        service:
        name: {{ .Values.appname }}
        port:
          number: 80
