apiVersion: v1
kind: PersistentVolume
metadata:
  name: tictactoe-pvc
  labels:
    app: tictactoe
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
