apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tictactoe-data
  namespace: tictactoe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
